# Generated by Django 5.2.8 on 2025-11-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_add_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('color', models.CharField(choices=[('black', 'Black'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('beige', 'Beige'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('natural', 'Natural Wood'), ('other', 'Other')], default='other', max_length=20)),
                ('material', models.CharField(choices=[('wood', 'Wood'), ('metal', 'Metal'), ('plastic', 'Plastic'), ('glass', 'Glass'), ('fabric', 'Fabric'), ('leather', 'Leather'), ('composite', 'Composite'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
